# Generated by Django 4.2.30 on 2026-07-26 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Hakkımızda', max_length=200, verbose_name='Başlık')),
                ('subtitle', models.CharField(blank=True, default='Doğal güzelliğinizi keşfedin', max_length=300, verbose_name='Alt Başlık')),
                ('content', models.TextField(default='Roselle Beauty & Care olarak doğal ve etkili formüllerle cildinize ve saçlarınıza değer katıyoruz.', verbose_name='Ana İçerik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Ana Görsel')),
                ('mission', models.TextField(blank=True, verbose_name='Misyonumuz')),
                ('vision', models.TextField(blank=True, verbose_name='Vizyonumuz')),
                ('story', models.TextField(blank=True, help_text='Markanın kuruluş hikayesi', verbose_name='Hikayemiz')),
                ('years_experience', models.PositiveIntegerField(default=5, verbose_name='Yıl Deneyim')),
                ('happy_customers', models.PositiveIntegerField(default=10000, verbose_name='Mutlu Müşteri')),
                ('products_count', models.PositiveIntegerField(default=20, verbose_name='Ürün Sayısı')),
                ('natural_ingredients', models.PositiveIntegerField(default=95, verbose_name='Doğal İçerik (%)')),
            ],
            options={
                'verbose_name': 'Hakkımızda',
                'verbose_name_plural': 'Hakkımızda',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Blog Kategorisi',
                'verbose_name_plural': 'Blog Kategorileri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BrandFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Metin')),
                ('icon', models.CharField(blank=True, default='fas fa-check', max_length=50, verbose_name='İkon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Marka Özelliği',
                'verbose_name_plural': 'Marka Özellikleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='İstanbul, Türkiye', verbose_name='Adres')),
                ('phone', models.CharField(default='+90 555 123 4567', max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(default='info@rosellebeauty.com', max_length=254, verbose_name='E-posta')),
                ('whatsapp', models.CharField(blank=True, help_text='Uluslararası format: 905551234567', max_length=20, verbose_name='WhatsApp Numarası')),
                ('map_embed', models.TextField(blank=True, verbose_name='Google Maps Embed Kodu')),
                ('map_link', models.URLField(blank=True, verbose_name='Google Maps Bağlantısı')),
                ('working_hours_weekday', models.CharField(default='09:00 - 21:00', max_length=50, verbose_name='Hafta İçi')),
                ('working_hours_saturday', models.CharField(default='10:00 - 20:00', max_length=50, verbose_name='Cumartesi')),
                ('working_hours_sunday', models.CharField(default='Kapalı', max_length=50, verbose_name='Pazar')),
            ],
            options={
                'verbose_name': 'İletişim Bilgileri',
                'verbose_name_plural': 'İletişim Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Soru')),
                ('answer', models.TextField(verbose_name='Cevap')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Sık Sorulan Soru',
                'verbose_name_plural': 'Sık Sorulan Sorular',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Başlık')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Görsel')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Galeri Görseli',
                'verbose_name_plural': 'Galeri Görselleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('subtitle', models.TextField(blank=True, verbose_name='Alt Başlık')),
                ('background_image', models.ImageField(upload_to='hero/', verbose_name='Arka Plan Görseli')),
                ('cta_text', models.CharField(blank=True, default='Keşfet', max_length=100, verbose_name='Buton Metni')),
                ('cta_link', models.CharField(blank=True, default='/urunler/', max_length=200, verbose_name='Buton Bağlantısı')),
                ('overlay_opacity', models.PositiveIntegerField(default=40, help_text='0-100 arası. Metnin okunabilirliği için arka plan kararma oranı.', verbose_name='Overlay Opaklığı (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Bannerlar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Bülten Abonesi',
                'verbose_name_plural': 'Bülten Aboneleri',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL Slug')),
                ('short_description', models.CharField(help_text='Ürün kartında görünecek kısa açıklama', max_length=300, verbose_name='Kısa Açıklama')),
                ('description', models.TextField(verbose_name='Detaylı Açıklama')),
                ('ingredients', models.TextField(blank=True, verbose_name='İçerik Bilgisi')),
                ('usage_info', models.TextField(blank=True, verbose_name='Kullanım Bilgisi')),
                ('volume', models.CharField(blank=True, help_text='Ör: 50 ML / 1.69 fl.oz.', max_length=50, verbose_name='Hacim/Boyut')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Ana Görsel')),
                ('image_hover', models.ImageField(blank=True, help_text='Ürün kartında fare üzerine gelince gösterilecek görsel', null=True, upload_to='products/', verbose_name='Hover Görseli')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat (₺)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='İndirimli fiyat göstermek için eski fiyat', max_digits=10, null=True, verbose_name='Eski Fiyat (₺)')),
                ('badge', models.CharField(blank=True, choices=[('', 'Badge Yok'), ('yeni', 'Yeni'), ('cok-satan', 'Çok Satan'), ('indirim', 'İndirimli'), ('ozel', 'Özel Ürün')], default='', max_length=20, verbose_name='Rozet')),
                ('dominant_color', models.CharField(default='#B8956A', help_text='Ürün kartında accent renk olarak kullanılacak (HEX)', max_length=7, verbose_name='Tema Rengi')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome ikon sınıfı (ör: fas fa-leaf)', max_length=50, verbose_name='İkon CSS Sınıfı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Kategori Görseli')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Ürün Kategorisi',
                'verbose_name_plural': 'Ürün Kategorileri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Hizmet Adı')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL Slug')),
                ('short_description', models.CharField(max_length=300, verbose_name='Kısa Açıklama')),
                ('description', models.TextField(blank=True, verbose_name='Detaylı Açıklama')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Hizmet Görseli')),
                ('icon', models.CharField(blank=True, default='fas fa-spa', max_length=50, verbose_name='İkon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Roselle Beauty & Care', max_length=200, verbose_name='Site Başlığı')),
                ('site_slogan', models.CharField(blank=True, default='Cildinize Değer Katın', max_length=300, verbose_name='Site Sloganı')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('logo_light', models.ImageField(blank=True, help_text='Footer ve koyu arka plan için açık renkli logo', null=True, upload_to='site/', verbose_name='Logo (Açık/Beyaz)')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
                ('meta_description', models.TextField(blank=True, default='Roselle Beauty & Care — Doğal güzelliğinizi keşfedin. Profesyonel cilt ve saç bakım ürünleri.', verbose_name='Meta Açıklama')),
                ('meta_keywords', models.CharField(blank=True, default='roselle beauty, cilt bakım, saç bakım, serum, doğal kozmetik', max_length=500, verbose_name='Anahtar Kelimeler')),
                ('footer_text', models.TextField(blank=True, default='© 2024 Roselle Beauty & Care. Tüm hakları saklıdır.', verbose_name='Footer Metni')),
                ('footer_description', models.TextField(blank=True, default='Doğal ve etkili formüllerle cildinize ve saçlarınıza değer katıyoruz.', verbose_name='Footer Açıklama')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Uluslararası format: 905551234567', max_length=20, verbose_name='WhatsApp Numarası')),
                ('whatsapp_default_message', models.CharField(blank=True, default='Merhaba, ürünleriniz hakkında bilgi almak istiyorum.', max_length=500, verbose_name='WhatsApp Varsayılan Mesaj')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('google_business', 'Google İşletme'), ('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn')], max_length=20, verbose_name='Platform')),
                ('url', models.URLField(verbose_name='Bağlantı URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Sosyal Medya',
                'verbose_name_plural': 'Sosyal Medya',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Ünvan/Meslek')),
                ('text', models.TextField(verbose_name='Yorum')),
                ('rating', models.PositiveIntegerField(default=5, help_text='1-5 arası puan', verbose_name='Puan')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Fotoğraf')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Müşteri Yorumu',
                'verbose_name_plural': 'Müşteri Yorumları',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Görsel')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt Metin')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Görseli',
                'verbose_name_plural': 'Ürün Görselleri',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.productcategory', verbose_name='Kategori'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL Slug')),
                ('excerpt', models.TextField(help_text='Blog listesinde görünecek kısa özet', max_length=500, verbose_name='Özet')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('cover_image', models.ImageField(upload_to='blog/', verbose_name='Kapak Görseli')),
                ('author', models.CharField(default='Roselle Beauty', max_length=100, verbose_name='Yazar')),
                ('read_time', models.PositiveIntegerField(default=5, verbose_name='Okuma Süresi (dk)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayınlandı')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO Açıklama')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayın Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.blogcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-published_at'],
            },
        ),
    ]
