# Generated by Django 4.2.30 on 2026-07-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_old_price_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_reviews_widget_code',
            field=models.TextField(blank=True, help_text='Elfsight, Trustpilot veya benzeri platformlardan aldığınız embed kodunu buraya yapıştırın. Bu kod aktifse, sitemizdeki yorumlar kısmında gösterilecektir.', verbose_name='Google Yorumlar Widget Kodu'),
        ),
    ]
